version: '3.8'
services:
  cbm-api:
    container_name: cbm-Api
    build: .
    environment:
      PORT: "${CBM_PORT}"
      GIN_MODE: debug
    ports:
      - ${CBM_PORT}:${CBM_PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/cbm-api/

volumes:
  api:
