version: '3.1'
services:
  cbm-api:
    container_name: cbm-Api
    build: .
    environment:
      PORT: "${CBM_PORT}"
      GIN_MODE: release
    ports:
      - ${CBM_PORT}:${CBM_PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/cbm-api/
      - ${HOME}/.cbm/watcher.toml:/watcher.toml

volumes:
  api:
