version: '3.8'
services:
  cbm-api:
    container_name: cbm-Api
    build: .
    environment:
      PORT: "${PORT}"
      GIN_MODE: release
    ports:
      - ${PORT}:${PORT}
#      - 5342:5342
    restart: on-failure
    volumes:
      - api:/usr/src/cbm-api/

volumes:
  api:
