[common]
    bin = "mysh" # Optional
    refBin = "tcsh" # Optional

    [common.options]
        repeat = 5 # Optional
        time = false # Optional
        timeout = 5 # in seconds, Optional

[[Test]]
    name = "Help"
    desc = "Will display CBM's help." # Optional
    args = ["-h"] # Optional
    refArgs = ["-h"] # Optional

    [Test.expected]
        status = 0
        stdout = "Hello world" # Optional
        stdoutFile = "nope" # Either this or stdout - Optional
        stderr = "lol" # Optional
        stderrFile = "lol" # Either this or stdout - Optional

    [Test.interactions]
        stdoutPipe = "yes life" # Optional
        stderrPipe = "bonjour" # Optional
        stdin = "yes life" # Optional
        stdinFile = "yes life" # Optional
        pre = "42" # Optional
        post = "yes life" # Optional
        env = "yes life" # Optional
        addEnv = "yes life" # Optional

    [Test.options]
        repeat = 10 # Optional
        time = true # Optional
        shouldFail = false # Optional
        timeout = 10 # Optional

[[Test]]
    name = "others"
    desc = "Will display CBM's help." # Optional
    args = ["-h"] # Optional
    refArgs = ["-h"] # Optional

    [Test.expected]
        status = 0
        stdout = "Hello world" # Optional
