version: '3.8'
services:
  cbm-api:
    container_name: cbm-Api
    build: .
    environment:
      API_PORT: 5342
      API_SECRET: 98hbun98h
    ports:
      - 5342:5342
    restart: on-failure
    volumes:
      - api:/usr/src/cbm-api/

#  fullstack-postgres:
#    image: postgres:latest
#    container_name: full_db_postgres
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#      - DATABASE_HOST=${DB_HOST}
#    ports:
#      - '5432:5432'
#    volumes:
#      - database_postgres:/var/lib/postgresql/data
#    networks:
#      - fullstack

volumes:
  api:

# Networks to be created to facilitate communication between containers
#networks:
#  fullstack:
#    driver: bridge

